# frozen_string_literal: true

source "https://rubygems.org"

gem 'capybara'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'report_builder'
gem 'rspec'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
